package agent

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"github.com/qingchang/Blood-on-the-Clocktower-auto-dm/internal/types"
)

type Agent interface {
	Name() string
	MaybeNarrate(ctx context.Context, event types.Event, viewer types.Viewer) *types.Event
}

type Narrator struct {
	logger *zap.Logger
}

func NewNarrator(logger *zap.Logger) *Narrator {
	return &Narrator{logger: logger}
}

func (n *Narrator) Name() string { return "narrator_stub" }

func (n *Narrator) MaybeNarrate(ctx context.Context, event types.Event, viewer types.Viewer) *types.Event {
	if event.EventType != "public.chat" {
		return nil
	}
	payload := map[string]string{
		"hint": "This is a lightweight system hint generated by the narrator stub.",
	}
	b, err := json.Marshal(payload)
	if err != nil {
		n.logger.Warn("failed to marshal hint", zap.Error(err))
		return nil
	}
	return &types.Event{
		RoomID:            event.RoomID,
		Seq:               0,
		EventID:           uuid.NewString(),
		EventType:         "system_hint",
		ActorUserID:       "agent",
		CausationCommand:  event.CausationCommand,
		Payload:           b,
		ServerTimestampMs: time.Now().UnixMilli(),
	}
}
